# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true
markdown: kramdown

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : Chaplin
tagline: An Application Architecture Using Backbone.js

# The production_url is only used when full-domain names are needed
# such as sitemap.txt Most places should use BASE_PATH for urls
production_url : http://chaplinjs.github.com

BASE_PATH: "/"

current_version: '1.0'

versions:
  '0.3': '/0/3/'
  '1.0': '/1/0/'

menu:

